### PR TITLE
use unmodified data for sig check (bug 1141640-two)

### PR DESCRIPTION
**Pull request by andymckay**

### CODE REVIEW

**Comment by kumar303** [comment]
Can you add a test that uses a field with a dash in the name so that the signature check fails unless you use the unmodified data?

**Comment by andymckay** [comment]
The test I altered does that now, it's what the test was meant to be doing. But `is_called_with` doesn't exist and passes because it calls the mock. Fixing the test shows the error.

**Comment by kumar303** [comment]
ok, if the test fails when you swap in ``self.data`` then I'm happy. r+

**Comment by kumar303** [comment]
> But is_called_with doesn't exist and passes because it calls the mock.

Sigh. I want to stop that from ever happening somehow.

**Pull request merged**
