### PR TITLE
make sure we start at the beginning of the day

### PR DESCRIPTION
**Pull request by andymckay**

### CODE REVIEW

**Comment by kumar303** [comment]
this might be a little more straightforward by putting this in setUp:

    self.first = Transaction.objects.create(...)
    self.start_date = self.first.created.date()

but not completely necessary

**Comment by kumar303** [comment]
r+wc

**Comment by andymckay** [comment]
I like that because it won't fail at 11:59.

**Comment by kumar303** [comment]
Yep, I was going to mention that but no one should be running tests at 11:59 ;)

**Pull request merged**
